### Jobs for updating Prow config

presubmits:
  verult-prowbot/Cirq:
  - name: prow-checkconfig
    branches:
    - master
    decorate: true
    run_if_changed: '^prow/'
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:latest
        imagePullPolicy: Always
        command:
        - /checkconfig
        args:
        - --config-path=./prow/config.yaml
        - --job-config-path=./prow/jobs
        - --plugin-config=./prow/plugins.yaml

postsubmits:
  verult-prowbot/Cirq:
  - name: prow-branchprotector
    decorate: true
    run_if_changed: '^(prow/config.yaml|prow/jobs/.*)$'
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-prow/branchprotector:latest
        command:
        - /app/prow/cmd/branchprotector/app.binary
        args:
        - --config-path=./prow/config.yaml
        - --job-config-path=./prow/jobs
        - --github-token-path=/etc/oauth-token/oauth
        - --confirm
        volumeMounts:
        - name: oauth-token
          mountPath: "/etc/oauth-token"
          readOnly: true
      volumes:
      - name: oauth-token
        secret:
          secretName: oauth-token
